source 'http://rubygems.org'

gem 'rails', '3.0.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'nifty-generators'
gem 'faker'
gem 'populator'
gem 'gravtastic'
gem 'jrails'
gem 'ruby-net-ldap'
gem 'oauth'
gem 'mysql'
gem 'mail'
#gem 'rake', '0.8.7'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
#gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
gem "bcrypt-ruby", :require => "bcrypt"
gem "mocha", :group => :test
